// screens/LandingPage.tsx
// Displays app name, tagline, and a "Start Planning" button that navigates to PlannerScreen.

import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
// Remove LinearGradient import
// import { LinearGradient } from 'expo-linear-gradient';
// Consider adding an icon library later like: import Icon from 'react-native-vector-icons/MaterialIcons';

const LandingPage = ({ navigation }: any) => {
  return (
    // Replace LinearGradient with a standard View
    <View style={styles.wrapper}>
      <ScrollView style={styles.scrollView} contentContainerStyle={styles.container}>
        {/* Hero Section */}
        {/* <Icon name="flight-takeoff" size={60} color="#FFF" style={styles.heroIcon} /> */}
        <Text style={styles.title}>JalanAI</Text>
        <Text style={styles.tagline}>Your AI-powered Malaysian travel companion</Text>

        <TouchableOpacity
          style={styles.button}
          onPress={() => navigation.navigate('Planner')} // Navigates to the screen defined in App.tsx
        >
          <Text style={styles.buttonText}>Start Planning Your Trip</Text>
        </TouchableOpacity>

        {/* How it Works Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>How It Works</Text>
          <View style={styles.step}>
            {/* <Icon name="chat" size={24} color="#555" /> */}
            <Text style={styles.stepText}>1. <Text style={styles.bold}>Chat:</Text> Tell us your travel preferences.</Text>
          </View>
          <View style={styles.step}>
            {/* <Icon name="map" size={24} color="#555" /> */}
            <Text style={styles.stepText}>2. <Text style={styles.bold}>Plan:</Text> Get a personalized itinerary generated by AI.</Text>
          </View>
          <View style={styles.step}>
            {/* <Icon name="book-online" size={24} color="#555" /> */}
            <Text style={styles.stepText}>3. <Text style={styles.bold}>Book:</Text> Confirm flights, hotels & tours in one place.</Text>
          </View>
        </View>

        {/* Features Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Why Choose JalanAI?</Text>
          <Text style={styles.featureText}>✨ <Text style={styles.bold}>Smart Personalization:</Text> AI crafts trips unique to you.</Text>
          <Text style={styles.featureText}>⏱️ <Text style={styles.bold}>Effortless Planning:</Text> Save time with automated suggestions.</Text>
          <Text style={styles.featureText}>✅ <Text style={styles.bold}>One-Stop Booking:</Text> Seamlessly book everything you need.</Text>
        </View>

      </ScrollView>
    </View>
  );
};

export default LandingPage;

const styles = StyleSheet.create({
  // Remove gradientContainer style
  // gradientContainer: { ... },
  wrapper: { // New style for the main background View
    flex: 1,
    backgroundColor: '#26A69A', // Nature-inspired teal
  },
  scrollView: {
    flex: 1,
    // No background color needed here
  },
  container: {
    // No background color needed here
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  // heroIcon: { ... },
  title: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#FFFFFF', // Change title color to white for contrast
    marginBottom: 10,
    textAlign: 'center',
  },
  tagline: {
    fontSize: 17,
    color: '#E0F2F1', // Lighter teal/white for contrast
    marginBottom: 35,
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  button: {
    backgroundColor: '#FFA500', // Change button color (e.g., Orange)
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 12,
    marginBottom: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  buttonText: {
    color: '#1c1c1e', // Dark text on orange button
    fontSize: 17,
    fontWeight: '600',
  },
  section: {
    width: '100%',
    marginBottom: 35,
    padding: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.95)', // Slightly less transparent white
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#004D40', // Darker teal for section titles
    marginBottom: 15,
    textAlign: 'center',
  },
  step: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  stepText: {
    fontSize: 16,
    color: '#37474F', // Dark grey/blue text
    marginLeft: 8,
    lineHeight: 22,
  },
  featureText: {
    fontSize: 16,
    color: '#37474F', // Dark grey/blue text
    marginBottom: 10,
    lineHeight: 22,
  },
  bold: {
    fontWeight: 'bold',
  },
});
